export const ranks = [
    {
        name: "Page",
        minBags: 0,
        maxBags: 499,
        failedLimit: Infinity,
        bagLimit: 25,
        restrictions: "Cannot order more bags until current operation is completed successfully.",
        perks: "Cannot order more bags until current operation is completed successfully.",
        image: require('../assets/images/avatars/page-avatar.png'),
    },
    {
        name: "Squire",
        minBags: 500,
        maxBags: 999,
        failedLimit: 20,
        bagLimit: 50,
        perks: "Can order more bags before completing the current operation.",
        requirements: "No more than 10 failed missions in the last 100 missions.",
        image: require('../assets/images/avatars/squire-avatar.png'),
    },
    {
        name: "Knight",
        minBags: 1000,
        maxBags: 4999,
        failedLimit: 5,
        bagLimit: 100,
        perks: "Unlocks mission bonuses.",
        requirements: "No more than 5 failed missions in the last 100 missions.",
        image: require('../assets/images/avatars/knight-avatar.png'),
    },
    {
        name: "Lord",
        minBags: 5000,
        maxBags: Infinity,
        failedLimit: 5,
        bagLimit: 200,
        perks: "Gains access to the distribution program.",
        requirements: "No more than 5 failed missions in the last 100 missions.",
        image: require('../assets/images/avatars/lord-avatar.png'),
    },
]; 